### ISSUE TITLE
What is the function of the app.webmanifest file in your code?

### ISSUE THREAD

**Issue by RealAbdurRehman** [sapientabdullah/TechClub-Repo#1]
https://github.com/sapientabdullah/TechClub-Repo/blob/main/Tally%20Counter/app.webmanifest

**Comment by sapientabdullah** [comment]
When users install web applications to their home screen or desktop, the manifest allows the web app to pop up in a separate window without the browser’s address bar or navigation controls, like a native app. Just add the app.webmanifest file into your project and see!

**Comment by RealAbdurRehman** [comment]
Could you make the answer, well, simple?
